version: '3.8'

services:
  estetica-frontend:
    # Mantenemos esto igual, ya vimos que funciona perfecto
    image: ghcr.io/joel110311/estetica-dashboard:latest
    networks:
      - SociosNet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.estetica.rule=Host(`estetica.logicapp.net`)"
        - "traefik.http.routers.estetica.entrypoints=websecure"
        - "traefik.http.routers.estetica.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.estetica.loadbalancer.server.port=80"
        - "traefik.docker.network=SociosNet"

  estetica-backend:
    # CAMBIO IMPORTANTE: Usamos esta imagen que es 100% fiable
    image: muchobien/pocketbase:latest
    # El comando interno cambia ligeramente para esta imagen
    command: /pb/pocketbase serve --http=0.0.0.0:8090
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - SociosNet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Aseg√∫rate de haber creado el subdominio api-estetica en tus DNS
        - "traefik.http.routers.estetica-api.rule=Host(`api-estetica.logicapp.net`)"
        - "traefik.http.routers.estetica-api.entrypoints=websecure"
        - "traefik.http.routers.estetica-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.estetica-api.loadbalancer.server.port=8090"
        - "traefik.docker.network=SociosNet"

volumes:
  pb_data:

networks:
  SociosNet:
    external: true
